apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  labels:
    app: banking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
      - name: banking-app
        image: anirudhabhi/banking-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: banking-app-eta-np-service
  labels:
    app: banking-app
spec:
  selector:
    app: banking-app

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8082
    targetPort: 8082
